### ISSUE TITLE
useragents.rb:2:in `require_relative'

### ISSUE THREAD

**Issue by wellsmuker** [debbbbie/useragents-rb#6]
/Users/wells/.rvm/gems/ruby-2.3.2/gems/useragents-0.1.6/lib/useragents.rb:2:in `require_relative': cannot load such file -- /Users/wells/.rvm/gems/ruby-2.3.2/gems/useragents-0.1.6/lib/useragents/fetch (LoadError)
	from /Users/wells/.rvm/gems/ruby-2.3.2/gems/useragents-0.1.6/lib/useragents.rb:2:in `<top (required)>'
	from /Users/wells/.rvm/rubies/ruby-2.3.2/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /Users/wells/.rvm/rubies/ruby-2.3.2/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Users/wells/.rvm/rubies/ruby-2.3.2/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from useragent.rb:1:in `<main>'

**Comment by elbarto132** [comment]
+1

**Comment by sergiopena** [comment]
+1

**Comment by MachLearnPort** [comment]
I ran into a similar problem. I was able to get rid of the error by removing  `require 'zlib'` and
`require_relative 'useragents/fetch'` in the useragents.rb file. I was missing the useragents.txt file, which I added.

**Comment by pedroanisio** [comment]
+1
